export const SurahName = [
  {
    number: 1,
    name: 'سُورَةُ ٱلْفَاتِحَةِ',
    englishName: 'Al-Faatiha',
    englishNameTranslation: 'The Opening',
    revelationType: 'Meccan',
    verses: 7,
  },
  {
    number: 2,
    name: 'سُورَةُ البَقَرَةِ',
    englishName: 'Al-Baqara',
    englishNameTranslation: 'The Cow',
    revelationType: 'Medinan',
    verses: 286,
  },
  {
    number: 3,
    name: 'سُورَةُ آلِ عِمۡرَانَ',
    englishName: 'Aal-i-Imraan',
    englishNameTranslation: 'The Family of Imraan',
    revelationType: 'Medinan',
    verses: 200,
  },
  {
    number: 4,
    name: 'سُورَةُ النِّسَاءِ',
    englishName: 'An-Nisaa',
    englishNameTranslation: 'The Women',
    revelationType: 'Medinan',
    verses: 176,
  },
  {
    number: 5,
    name: 'سُورَةُ المَائـِدَةِ',
    englishName: 'Al-Maaida',
    englishNameTranslation: 'The Table',
    revelationType: 'Medinan',
    verses: 120,
  },
  {
    number: 6,
    name: 'سُورَةُ الأَنۡعَامِ',
    englishName: "Al-An'aam",
    englishNameTranslation: 'The Cattle',
    revelationType: 'Meccan',
    verses: 165,
  },
  {
    number: 7,
    name: 'سُورَةُ الأَعۡرَافِ',
    englishName: "Al-A'raaf",
    englishNameTranslation: 'The Heights',
    revelationType: 'Meccan',
    verses: 206,
  },
  {
    number: 8,
    name: 'سُورَةُ الأَنفَالِ',
    englishName: 'Al-Anfaal',
    englishNameTranslation: 'The Spoils of War',
    revelationType: 'Medinan',
    verses: 75,
  },
  {
    number: 9,
    name: 'سُورَةُ التَّوۡبَةِ',
    englishName: 'At-Tawba',
    englishNameTranslation: 'The Repentance',
    revelationType: 'Medinan',
    verses: 129,
  },
  {
    number: 10,
    name: 'سُورَةُ يُونُسَ',
    englishName: 'Yunus',
    englishNameTranslation: 'Jonas',
    revelationType: 'Meccan',
    verses: 109,
  },
  {
    number: 11,
    name: 'سُورَةُ هُودٍ',
    englishName: 'Hud',
    englishNameTranslation: 'Hud',
    revelationType: 'Meccan',
    verses: 123,
  },
  {
    number: 12,
    name: 'سُورَةُ يُوسُفَ',
    englishName: 'Yusuf',
    englishNameTranslation: 'Joseph',
    revelationType: 'Meccan',
    verses: 111,
  },
  {
    number: 13,
    name: 'سُورَةُ الرَّعۡدِ',
    englishName: "Ar-Ra'd",
    englishNameTranslation: 'The Thunder',
    revelationType: 'Medinan',
    verses: 43,
  },
  {
    number: 14,
    name: 'سُورَةُ إِبۡرَاهِيمَ',
    englishName: 'Ibrahim',
    englishNameTranslation: 'Abraham',
    revelationType: 'Meccan',
    verses: 52,
  },
  {
    number: 15,
    name: 'سُورَةُ الحِجۡرِ',
    englishName: 'Al-Hijr',
    englishNameTranslation: 'The Rock',
    revelationType: 'Meccan',
    verses: 99,
  },
  {
    number: 16,
    name: 'سُورَةُ النَّحۡلِ',
    englishName: 'An-Nahl',
    englishNameTranslation: 'The Bee',
    revelationType: 'Meccan',
    verses: 128,
  },
  {
    number: 17,
    name: 'سُورَةُ الإِسۡرَاءِ',
    englishName: 'Al-Israa',
    englishNameTranslation: 'The Night Journey',
    revelationType: 'Meccan',
    verses: 111,
  },
  {
    number: 18,
    name: 'سُورَةُ الكَهۡفِ',
    englishName: 'Al-Kahf',
    englishNameTranslation: 'The Cave',
    revelationType: 'Meccan',
    verses: 110,
  },
  {
    number: 19,
    name: 'سُورَةُ مَرۡيَمَ',
    englishName: 'Maryam',
    englishNameTranslation: 'Mary',
    revelationType: 'Meccan',
    verses: 98,
  },
  {
    number: 20,
    name: 'سُورَةُ طه',
    englishName: 'Taa-Haa',
    englishNameTranslation: 'Taa-Haa',
    revelationType: 'Meccan',
    verses: 135,
  },
  {
    number: 21,
    name: 'سُورَةُ الأَنبِيَاءِ',
    englishName: 'Al-Anbiyaa',
    englishNameTranslation: 'The Prophets',
    revelationType: 'Meccan',
    verses: 112,
  },
  {
    number: 22,
    name: 'سُورَةُ الحَجِّ',
    englishName: 'Al-Hajj',
    englishNameTranslation: 'The Pilgrimage',
    revelationType: 'Medinan',
    verses: 78,
  },
  {
    number: 23,
    name: 'سُورَةُ المُؤۡمِنُونَ',
    englishName: 'Al-Muminoon',
    englishNameTranslation: 'The Believers',
    revelationType: 'Meccan',
    verses: 118,
  },
  {
    number: 24,
    name: 'سُورَةُ النُّورِ',
    englishName: 'An-Noor',
    englishNameTranslation: 'The Light',
    revelationType: 'Medinan',
    verses: 64,
  },
  {
    number: 25,
    name: 'سُورَةُ الفُرۡقَانِ',
    englishName: 'Al-Furqaan',
    englishNameTranslation: 'The Criterion',
    revelationType: 'Meccan',
    verses: 77,
  },
  {
    number: 26,
    name: 'سُورَةُ الشُّعَرَاءِ',
    englishName: "Ash-Shu'araa",
    englishNameTranslation: 'The Poets',
    revelationType: 'Meccan',
    verses: 227,
  },
  {
    number: 27,
    name: 'سُورَةُ النَّمۡلِ',
    englishName: 'An-Naml',
    englishNameTranslation: 'The Ant',
    revelationType: 'Meccan',
    verses: 93,
  },
  {
    number: 28,
    name: 'سُورَةُ القَصَصِ',
    englishName: 'Al-Qasas',
    englishNameTranslation: 'The Stories',
    revelationType: 'Meccan',
    verses: 88,
  },
  {
    number: 29,
    name: 'سُورَةُ العَنكَبُوتِ',
    englishName: 'Al-Ankaboot',
    englishNameTranslation: 'The Spider',
    revelationType: 'Meccan',
    verses: 69,
  },
  {
    number: 30,
    name: 'سُورَةُ الرُّومِ',
    englishName: 'Ar-Room',
    englishNameTranslation: 'The Romans',
    revelationType: 'Meccan',
    verses: 60,
  },
  {
    number: 31,
    name: 'سُورَةُ لُقۡمَانَ',
    englishName: 'Luqman',
    englishNameTranslation: 'Luqman',
    revelationType: 'Meccan',
    verses: 34,
  },
  {
    number: 32,
    name: 'سُورَةُ السَّجۡدَةِ',
    englishName: 'As-Sajda',
    englishNameTranslation: 'The Prostration',
    revelationType: 'Meccan',
    verses: 30,
  },
  {
    number: 33,
    name: 'سُورَةُ الأَحۡزَابِ',
    englishName: 'Al-Ahzaab',
    englishNameTranslation: 'The Clans',
    revelationType: 'Medinan',
    verses: 73,
  },
  {
    number: 34,
    name: 'سُورَةُ سَبَإٍ',
    englishName: 'Saba',
    englishNameTranslation: 'Sheba',
    revelationType: 'Meccan',
    verses: 54,
  },
  {
    number: 35,
    name: 'سُورَةُ فَاطِرٍ',
    englishName: 'Faatir',
    englishNameTranslation: 'The Originator',
    revelationType: 'Meccan',
    verses: 45,
  },
  {
    number: 36,
    name: 'سُورَةُ يسٓ',
    englishName: 'Yaseen',
    englishNameTranslation: 'Yaseen',
    revelationType: 'Meccan',
    verses: 83,
  },
  {
    number: 37,
    name: 'سُورَةُ الصَّافَّاتِ',
    englishName: 'As-Saaffaat',
    englishNameTranslation: 'Those drawn up in Ranks',
    revelationType: 'Meccan',
    verses: 182,
  },
  {
    number: 38,
    name: 'سُورَةُ صٓ',
    englishName: 'Saad',
    englishNameTranslation: 'The letter Saad',
    revelationType: 'Meccan',
    verses: 88,
  },
  {
    number: 39,
    name: 'سُورَةُ الزُّمَرِ',
    englishName: 'Az-Zumar',
    englishNameTranslation: 'The Groups',
    revelationType: 'Meccan',
    verses: 75,
  },
  {
    number: 40,
    name: 'سُورَةُ غَافِرٍ',
    englishName: 'Ghafir',
    englishNameTranslation: 'The Forgiver',
    revelationType: 'Meccan',
    verses: 85,
  },
  {
    number: 41,
    name: 'سُورَةُ فُصِّلَتۡ',
    englishName: 'Fussilat',
    englishNameTranslation: 'Explained in detail',
    revelationType: 'Meccan',
    verses: 54,
  },
  {
    number: 42,
    name: 'سُورَةُ الشُّورَىٰ',
    englishName: 'Ash-Shura',
    englishNameTranslation: 'Consultation',
    revelationType: 'Meccan',
    verses: 53,
  },
  {
    number: 43,
    name: 'سُورَةُ الزُّخۡرُفِ',
    englishName: 'Az-Zukhruf',
    englishNameTranslation: 'Ornaments of gold',
    revelationType: 'Meccan',
    verses: 89,
  },
  {
    number: 44,
    name: 'سُورَةُ الدُّخَانِ',
    englishName: 'Ad-Dukhaan',
    englishNameTranslation: 'The Smoke',
    revelationType: 'Meccan',
    verses: 59,
  },
  {
    number: 45,
    name: 'سُورَةُ الجَاثِيَةِ',
    englishName: 'Al-Jaathiya',
    englishNameTranslation: 'Crouching',
    revelationType: 'Meccan',
    verses: 37,
  },
  {
    number: 46,
    name: 'سُورَةُ الأَحۡقَافِ',
    englishName: 'Al-Ahqaf',
    englishNameTranslation: 'The Dunes',
    revelationType: 'Meccan',
    verses: 35,
  },
  {
    number: 47,
    name: 'سُورَةُ مُحَمَّدٍ',
    englishName: 'Muhammad',
    englishNameTranslation: 'Muhammad',
    revelationType: 'Medinan',
    verses: 38,
  },
  {
    number: 48,
    name: 'سُورَةُ الفَتۡحِ',
    englishName: 'Al-Fath',
    englishNameTranslation: 'The Victory',
    revelationType: 'Medinan',
    verses: 29,
  },
  {
    number: 49,
    name: 'سُورَةُ الحُجُرَاتِ',
    englishName: 'Al-Hujuraat',
    englishNameTranslation: 'The Inner Apartments',
    revelationType: 'Medinan',
    verses: 18,
  },
  {
    number: 50,
    name: 'سُورَةُ قٓ',
    englishName: 'Qaaf',
    englishNameTranslation: 'The letter Qaaf',
    revelationType: 'Meccan',
    verses: 45,
  },
  {
    number: 51,
    name: 'سُورَةُ الذَّارِيَاتِ',
    englishName: 'Adh-Dhaariyat',
    englishNameTranslation: 'The Winnowing Winds',
    revelationType: 'Meccan',
    verses: 60,
  },
  {
    number: 52,
    name: 'سُورَةُ الطُّورِ',
    englishName: 'At-Tur',
    englishNameTranslation: 'The Mount',
    revelationType: 'Meccan',
    verses: 49,
  },
  {
    number: 53,
    name: 'سُورَةُ النَّجۡمِ',
    englishName: 'An-Najm',
    englishNameTranslation: 'The Star',
    revelationType: 'Meccan',
    verses: 62,
  },
  {
    number: 54,
    name: 'سُورَةُ القَمَرِ',
    englishName: 'Al-Qamar',
    englishNameTranslation: 'The Moon',
    revelationType: 'Meccan',
    verses: 55,
  },
  {
    number: 55,
    name: 'سُورَةُ الرَّحۡمَٰن',
    englishName: 'Ar-Rahmaan',
    englishNameTranslation: 'The Beneficent',
    revelationType: 'Medinan',
    verses: 78,
  },
  {
    number: 56,
    name: 'سُورَةُ الوَاقِعَةِ',
    englishName: 'Al-Waaqia',
    englishNameTranslation: 'The Inevitable',
    revelationType: 'Meccan',
    verses: 96,
  },
  {
    number: 57,
    name: 'سُورَةُ الحَدِيدِ',
    englishName: 'Al-Hadid',
    englishNameTranslation: 'The Iron',
    revelationType: 'Medinan',
    verses: 29,
  },
  {
    number: 58,
    name: 'سُورَةُ المُجَادلَةِ',
    englishName: 'Al-Mujaadila',
    englishNameTranslation: 'The Pleading Woman',
    revelationType: 'Medinan',
    verses: 22,
  },
  {
    number: 59,
    name: 'سُورَةُ الحَشۡرِ',
    englishName: 'Al-Hashr',
    englishNameTranslation: 'The Exile',
    revelationType: 'Medinan',
    verses: 24,
  },
  {
    number: 60,
    name: 'سُورَةُ المُمۡتَحنَةِ',
    englishName: 'Al-Mumtahana',
    englishNameTranslation: 'She that is to be examined',
    revelationType: 'Medinan',
    verses: 13,
  },
  {
    number: 61,
    name: 'سُورَةُ الصَّفِّ',
    englishName: 'As-Saff',
    englishNameTranslation: 'The Ranks',
    revelationType: 'Medinan',
    verses: 14,
  },
  {
    number: 62,
    name: 'سُورَةُ الجُمُعَةِ',
    englishName: "Al-Jumu'a",
    englishNameTranslation: 'Friday',
    revelationType: 'Medinan',
    verses: 11,
  },
  {
    number: 63,
    name: 'سُورَةُ المُنَافِقُونَ',
    englishName: 'Al-Munaafiqoon',
    englishNameTranslation: 'The Hypocrites',
    revelationType: 'Medinan',
    verses: 11,
  },
  {
    number: 64,
    name: 'سُورَةُ التَّغَابُنِ',
    englishName: 'At-Taghaabun',
    englishNameTranslation: 'Mutual Disillusion',
    revelationType: 'Medinan',
    verses: 18,
  },
  {
    number: 65,
    name: 'سُورَةُ الطَّلَاقِ',
    englishName: 'At-Talaaq',
    englishNameTranslation: 'Divorce',
    revelationType: 'Medinan',
    verses: 12,
  },
  {
    number: 66,
    name: 'سُورَةُ التَّحۡرِيمِ',
    englishName: 'At-Tahrim',
    englishNameTranslation: 'The Prohibition',
    revelationType: 'Medinan',
    verses: 12,
  },
  {
    number: 67,
    name: 'سُورَةُ المُلۡكِ',
    englishName: 'Al-Mulk',
    englishNameTranslation: 'The Sovereignty',
    revelationType: 'Meccan',
    verses: 30,
  },
  {
    number: 68,
    name: 'سُورَةُ القَلَمِ',
    englishName: 'Al-Qalam',
    englishNameTranslation: 'The Pen',
    revelationType: 'Meccan',
    verses: 52,
  },
  {
    number: 69,
    name: 'سُورَةُ الحَاقَّةِ',
    englishName: 'Al-Haaqqa',
    englishNameTranslation: 'The Reality',
    revelationType: 'Meccan',
    verses: 52,
  },
  {
    number: 70,
    name: 'سُورَةُ المَعَارِجِ',
    englishName: "Al-Ma'aarij",
    englishNameTranslation: 'The Ascending Stairways',
    revelationType: 'Meccan',
    verses: 44,
  },
  {
    number: 71,
    name: 'سُورَةُ نُوحٍ',
    englishName: 'Nooh',
    englishNameTranslation: 'Noah',
    revelationType: 'Meccan',
    verses: 28,
  },
  {
    number: 72,
    name: 'سُورَةُ الجِنِّ',
    englishName: 'Al-Jinn',
    englishNameTranslation: 'The Jinn',
    revelationType: 'Meccan',
    verses: 28,
  },
  {
    number: 73,
    name: 'سُورَةُ المُزَّمِّلِ',
    englishName: 'Al-Muzzammil',
    englishNameTranslation: 'The Enshrouded One',
    revelationType: 'Meccan',
    verses: 20,
  },
  {
    number: 74,
    name: 'سُورَةُ المُدَّثِّرِ',
    englishName: 'Al-Muddaththir',
    englishNameTranslation: 'The Cloaked One',
    revelationType: 'Meccan',
    verses: 56,
  },
  {
    number: 75,
    name: 'سُورَةُ القِيَامَةِ',
    englishName: 'Al-Qiyaama',
    englishNameTranslation: 'The Resurrection',
    revelationType: 'Meccan',
    verses: 40,
  },
  {
    number: 76,
    name: 'سُورَةُ الإِنسَانِ',
    englishName: 'Al-Insaan',
    englishNameTranslation: 'Man',
    revelationType: 'Medinan',
    verses: 31,
  },
  {
    number: 77,
    name: 'سُورَةُ المُرۡسَلَاتِ',
    englishName: 'Al-Mursalaat',
    englishNameTranslation: 'The Emissaries',
    revelationType: 'Meccan',
    verses: 50,
  },
  {
    number: 78,
    name: 'سُورَةُ النَّبَإِ',
    englishName: 'An-Naba',
    englishNameTranslation: 'The Announcement',
    revelationType: 'Meccan',
    verses: 40,
  },
  {
    number: 79,
    name: 'سُورَةُ النَّازِعَاتِ',
    englishName: "An-Naazi'aat",
    englishNameTranslation: 'Those who drag forth',
    revelationType: 'Meccan',
    verses: 46,
  },
  {
    number: 80,
    name: 'سُورَةُ عَبَسَ',
    englishName: 'Abasa',
    englishNameTranslation: 'He frowned',
    revelationType: 'Meccan',
    verses: 42,
  },
  {
    number: 81,
    name: 'سُورَةُ التَّكۡوِيرِ',
    englishName: 'At-Takwir',
    englishNameTranslation: 'The Overthrowing',
    revelationType: 'Meccan',
    verses: 29,
  },
  {
    number: 82,
    name: 'سُورَةُ الانفِطَارِ',
    englishName: 'Al-Infitaar',
    englishNameTranslation: 'The Cleaving',
    revelationType: 'Meccan',
    verses: 19,
  },
  {
    number: 83,
    name: 'سُورَةُ المُطَفِّفِينَ',
    englishName: 'Al-Mutaffifin',
    englishNameTranslation: 'Defrauding',
    revelationType: 'Meccan',
    verses: 36,
  },
  {
    number: 84,
    name: 'سُورَةُ الانشِقَاقِ',
    englishName: 'Al-Inshiqaaq',
    englishNameTranslation: 'The Splitting Open',
    revelationType: 'Meccan',
    verses: 25,
  },
  {
    number: 85,
    name: 'سُورَةُ البُرُوجِ',
    englishName: 'Al-Burooj',
    englishNameTranslation: 'The Constellations',
    revelationType: 'Meccan',
    verses: 22,
  },
  {
    number: 86,
    name: 'سُورَةُ الطَّارِقِ',
    englishName: 'At-Taariq',
    englishNameTranslation: 'The Morning Star',
    revelationType: 'Meccan',
    verses: 17,
  },
  {
    number: 87,
    name: 'سُورَةُ الأَعۡلَىٰ',
    englishName: "Al-A'laa",
    englishNameTranslation: 'The Most High',
    revelationType: 'Meccan',
    verses: 19,
  },
  {
    number: 88,
    name: 'سُورَةُ الغَاشِيَةِ',
    englishName: 'Al-Ghaashiya',
    englishNameTranslation: 'The Overwhelming',
    revelationType: 'Meccan',
    verses: 26,
  },
  {
    number: 89,
    name: 'سُورَةُ الفَجۡرِ',
    englishName: 'Al-Fajr',
    englishNameTranslation: 'The Dawn',
    revelationType: 'Meccan',
    verses: 30,
  },
  {
    number: 90,
    name: 'سُورَةُ البَلَدِ',
    englishName: 'Al-Balad',
    englishNameTranslation: 'The City',
    revelationType: 'Meccan',
    verses: 20,
  },
  {
    number: 91,
    name: 'سُورَةُ الشَّمۡسِ',
    englishName: 'Ash-Shams',
    englishNameTranslation: 'The Sun',
    revelationType: 'Meccan',
    verses: 15,
  },
  {
    number: 92,
    name: 'سُورَةُ اللَّيۡلِ',
    englishName: 'Al-Lail',
    englishNameTranslation: 'The Night',
    revelationType: 'Meccan',
    verses: 21,
  },
  {
    number: 93,
    name: 'سُورَةُ الضُّحَىٰ',
    englishName: 'Ad-Dhuhaa',
    englishNameTranslation: 'The Morning Hours',
    revelationType: 'Meccan',
    verses: 11,
  },
  {
    number: 94,
    name: 'سُورَةُ الشَّرۡحِ',
    englishName: 'Ash-Sharh',
    englishNameTranslation: 'The Consolation',
    revelationType: 'Meccan',
    verses: 8,
  },
  {
    number: 95,
    name: 'سُورَةُ التِّينِ',
    englishName: 'At-Tin',
    englishNameTranslation: 'The Fig',
    revelationType: 'Meccan',
    verses: 8,
  },
  {
    number: 96,
    name: 'سُورَةُ العَلَقِ',
    englishName: 'Al-Alaq',
    englishNameTranslation: 'The Clot',
    revelationType: 'Meccan',
    verses: 19,
  },
  {
    number: 97,
    name: 'سُورَةُ القَدۡرِ',
    englishName: 'Al-Qadr',
    englishNameTranslation: 'The Power, Fate',
    revelationType: 'Meccan',
    verses: 5,
  },
  {
    number: 98,
    name: 'سُورَةُ البَيِّنَةِ',
    englishName: 'Al-Bayyina',
    englishNameTranslation: 'The Evidence',
    revelationType: 'Medinan',
    verses: 8,
  },
  {
    number: 99,
    name: 'سُورَةُ الزَّلۡزَلَةِ',
    englishName: 'Az-Zalzala',
    englishNameTranslation: 'The Earthquake',
    revelationType: 'Medinan',
    verses: 8,
  },
  {
    number: 100,
    name: 'سُورَةُ العَادِيَاتِ',
    englishName: 'Al-Aadiyaat',
    englishNameTranslation: 'The Chargers',
    revelationType: 'Meccan',
    verses: 11,
  },
  {
    number: 101,
    name: 'سُورَةُ القَارِعَةِ',
    englishName: "Al-Qaari'a",
    englishNameTranslation: 'The Calamity',
    revelationType: 'Meccan',
    verses: 11,
  },
  {
    number: 102,
    name: 'سُورَةُ التَّكَاثُرِ',
    englishName: 'At-Takaathur',
    englishNameTranslation: 'Competition',
    revelationType: 'Meccan',
    verses: 8,
  },
  {
    number: 103,
    name: 'سُورَةُ العَصۡرِ',
    englishName: 'Al-Asr',
    englishNameTranslation: 'The Declining Day, Epoch',
    revelationType: 'Meccan',
    verses: 3,
  },
  {
    number: 104,
    name: 'سُورَةُ الهُمَزَةِ',
    englishName: 'Al-Humaza',
    englishNameTranslation: 'The Traducer',
    revelationType: 'Meccan',
    verses: 9,
  },
  {
    number: 105,
    name: 'سُورَةُ الفِيلِ',
    englishName: 'Al-Fil',
    englishNameTranslation: 'The Elephant',
    revelationType: 'Meccan',
    verses: 5,
  },
  {
    number: 106,
    name: 'سُورَةُ قُرَيۡشٍ',
    englishName: 'Quraish',
    englishNameTranslation: 'Quraysh',
    revelationType: 'Meccan',
    verses: 4,
  },
  {
    number: 107,
    name: 'سُورَةُ المَاعُونِ',
    englishName: "Al-Maa'un",
    englishNameTranslation: 'Almsgiving',
    revelationType: 'Meccan',
    verses: 7,
  },
  {
    number: 108,
    name: 'سُورَةُ الكَوۡثَرِ',
    englishName: 'Al-Kawthar',
    englishNameTranslation: 'Abundance',
    revelationType: 'Meccan',
    verses: 3,
  },
  {
    number: 109,
    name: 'سُورَةُ الكَافِرُونَ',
    englishName: 'Al-Kaafiroon',
    englishNameTranslation: 'The Disbelievers',
    revelationType: 'Meccan',
    verses: 6,
  },
  {
    number: 110,
    name: 'سُورَةُ النَّصۡرِ',
    englishName: 'An-Nasr',
    englishNameTranslation: 'Divine Support',
    revelationType: 'Medinan',
    verses: 3,
  },
  {
    number: 111,
    name: 'سُورَةُ المَسَدِ',
    englishName: 'Al-Masad',
    englishNameTranslation: 'The Palm Fibre',
    revelationType: 'Meccan',
    verses: 5,
  },
  {
    number: 112,
    name: 'سُورَةُ الإِخۡلَاصِ',
    englishName: 'Al-Ikhlaas',
    englishNameTranslation: 'Sincerity',
    revelationType: 'Meccan',
    verses: 4,
  },
  {
    number: 113,
    name: 'سُورَةُ الفَلَقِ',
    englishName: 'Al-Falaq',
    englishNameTranslation: 'The Dawn',
    revelationType: 'Meccan',
    verses: 5,
  },
  {
    number: 114,
    name: 'سُورَةُ النَّاسِ',
    englishName: 'An-Naas',
    englishNameTranslation: 'Mankind',
    revelationType: 'Meccan',
    verses: 6,
  },
];
